// <auto-generated />
using System;
using DataAccessLayer.Concrete.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(ShopContext))]
    [Migration("20230817135059_mig_1")]
    partial class mig_1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EntityLayer.Cart", b =>
                {
                    b.Property<double>("CartId")
                        .HasColumnType("float");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CartId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("EntityLayer.CartItem", b =>
                {
                    b.Property<double>("CartItemId")
                        .HasColumnType("float");

                    b.Property<double>("CartId")
                        .HasColumnType("float");

                    b.Property<double>("ProductId")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("CartItemId");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("EntityLayer.Category", b =>
                {
                    b.Property<double>("CategoryId")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 111111112.0,
                            Name = "category 1",
                            Url = "category-1"
                        },
                        new
                        {
                            CategoryId = 111111113.0,
                            Name = "category 2",
                            Url = "category-2"
                        },
                        new
                        {
                            CategoryId = 111111114.0,
                            Name = "category 3",
                            Url = "category-3"
                        },
                        new
                        {
                            CategoryId = 111111115.0,
                            Name = "category 4",
                            Url = "category-4"
                        },
                        new
                        {
                            CategoryId = 111111116.0,
                            Name = "category 5",
                            Url = "category-5"
                        },
                        new
                        {
                            CategoryId = 111111117.0,
                            Name = "category 6",
                            Url = "category-6"
                        },
                        new
                        {
                            CategoryId = 111111118.0,
                            Name = "category 7",
                            Url = "category-7"
                        },
                        new
                        {
                            CategoryId = 111111119.0,
                            Name = "category 8",
                            Url = "category-8"
                        },
                        new
                        {
                            CategoryId = 111111120.0,
                            Name = "category 9",
                            Url = "category-9"
                        });
                });

            modelBuilder.Entity("EntityLayer.ImageUrl", b =>
                {
                    b.Property<double>("Id")
                        .HasColumnType("float");

                    b.Property<double>("ProductId")
                        .HasColumnType("float");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ImageUrls");

                    b.HasData(
                        new
                        {
                            Id = 111111112.0,
                            ProductId = 111111112.0,
                            Url = "1.jpg"
                        },
                        new
                        {
                            Id = 111111113.0,
                            ProductId = 111111113.0,
                            Url = "1.jpg"
                        },
                        new
                        {
                            Id = 111111114.0,
                            ProductId = 111111114.0,
                            Url = "1.jpg"
                        },
                        new
                        {
                            Id = 111111115.0,
                            ProductId = 111111115.0,
                            Url = "1.jpg"
                        },
                        new
                        {
                            Id = 111111116.0,
                            ProductId = 111111116.0,
                            Url = "1.jpg"
                        },
                        new
                        {
                            Id = 111111117.0,
                            ProductId = 111111117.0,
                            Url = "1.jpg"
                        },
                        new
                        {
                            Id = 111111118.0,
                            ProductId = 111111118.0,
                            Url = "1.jpg"
                        },
                        new
                        {
                            Id = 111111119.0,
                            ProductId = 111111119.0,
                            Url = "1.jpg"
                        },
                        new
                        {
                            Id = 111111120.0,
                            ProductId = 111111120.0,
                            Url = "1.jpg"
                        });
                });

            modelBuilder.Entity("EntityLayer.Order", b =>
                {
                    b.Property<double>("OrderId")
                        .HasColumnType("float");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConversationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderState")
                        .HasColumnType("int");

                    b.Property<string>("PaymentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaymentType")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("EntityLayer.OrderItem", b =>
                {
                    b.Property<double>("OrderItemId")
                        .HasColumnType("float");

                    b.Property<double>("OrderId")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("ProductId")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("EntityLayer.Product", b =>
                {
                    b.Property<double>("ProductId")
                        .HasColumnType("float");

                    b.Property<string>("CreatedDate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHome")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ProductImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SalesCount")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 111111112.0,
                            CreatedDate = "2023/08/17 16:50:59",
                            Description = "urun aciklamasi 1",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 1",
                            Price = 10.0,
                            ProductImage = "1.jpg",
                            Quantity = 1,
                            SalesCount = 1,
                            UpdatedDate = "2023/08/17 16:50:59",
                            Url = "urun-1"
                        },
                        new
                        {
                            ProductId = 111111113.0,
                            CreatedDate = "2023/08/17 16:50:59",
                            Description = "urun aciklamasi 2",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 2",
                            Price = 10.0,
                            ProductImage = "1.jpg",
                            Quantity = 2,
                            SalesCount = 2,
                            UpdatedDate = "2023/08/17 16:50:59",
                            Url = "urun-2"
                        },
                        new
                        {
                            ProductId = 111111114.0,
                            CreatedDate = "2023/08/17 16:50:59",
                            Description = "urun aciklamasi 3",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 3",
                            Price = 10.0,
                            ProductImage = "1.jpg",
                            Quantity = 3,
                            SalesCount = 3,
                            UpdatedDate = "2023/08/17 16:50:59",
                            Url = "urun-3"
                        },
                        new
                        {
                            ProductId = 111111115.0,
                            CreatedDate = "2023/08/17 16:50:59",
                            Description = "urun aciklamasi 4",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 4",
                            Price = 10.0,
                            ProductImage = "1.jpg",
                            Quantity = 4,
                            SalesCount = 4,
                            UpdatedDate = "2023/08/17 16:50:59",
                            Url = "urun-4"
                        },
                        new
                        {
                            ProductId = 111111116.0,
                            CreatedDate = "2023/08/17 16:50:59",
                            Description = "urun aciklamasi 5",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 5",
                            Price = 10.0,
                            ProductImage = "1.jpg",
                            Quantity = 5,
                            SalesCount = 5,
                            UpdatedDate = "2023/08/17 16:50:59",
                            Url = "urun-5"
                        },
                        new
                        {
                            ProductId = 111111117.0,
                            CreatedDate = "2023/08/17 16:50:59",
                            Description = "urun aciklamasi 6",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 6",
                            Price = 10.0,
                            ProductImage = "1.jpg",
                            Quantity = 6,
                            SalesCount = 6,
                            UpdatedDate = "2023/08/17 16:50:59",
                            Url = "urun-6"
                        },
                        new
                        {
                            ProductId = 111111118.0,
                            CreatedDate = "2023/08/17 16:50:59",
                            Description = "urun aciklamasi 7",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 7",
                            Price = 10.0,
                            ProductImage = "1.jpg",
                            Quantity = 7,
                            SalesCount = 7,
                            UpdatedDate = "2023/08/17 16:50:59",
                            Url = "urun-7"
                        },
                        new
                        {
                            ProductId = 111111119.0,
                            CreatedDate = "2023/08/17 16:50:59",
                            Description = "urun aciklamasi 8",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 8",
                            Price = 10.0,
                            ProductImage = "1.jpg",
                            Quantity = 8,
                            SalesCount = 8,
                            UpdatedDate = "2023/08/17 16:50:59",
                            Url = "urun-8"
                        },
                        new
                        {
                            ProductId = 111111120.0,
                            CreatedDate = "2023/08/17 16:50:59",
                            Description = "urun aciklamasi 9",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 9",
                            Price = 10.0,
                            ProductImage = "1.jpg",
                            Quantity = 9,
                            SalesCount = 9,
                            UpdatedDate = "2023/08/17 16:50:59",
                            Url = "urun-9"
                        },
                        new
                        {
                            ProductId = 111111121.0,
                            CreatedDate = "2023/08/17 16:50:59",
                            Description = "urun aciklamasi 10",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 10",
                            Price = 10.0,
                            ProductImage = "1.jpg",
                            Quantity = 10,
                            SalesCount = 10,
                            UpdatedDate = "2023/08/17 16:50:59",
                            Url = "urun-10"
                        },
                        new
                        {
                            ProductId = 111111122.0,
                            CreatedDate = "2023/08/17 16:50:59",
                            Description = "urun aciklamasi 11",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 11",
                            Price = 10.0,
                            ProductImage = "1.jpg",
                            Quantity = 11,
                            SalesCount = 11,
                            UpdatedDate = "2023/08/17 16:50:59",
                            Url = "urun-11"
                        },
                        new
                        {
                            ProductId = 111111123.0,
                            CreatedDate = "2023/08/17 16:50:59",
                            Description = "urun aciklamasi 12",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 12",
                            Price = 10.0,
                            ProductImage = "1.jpg",
                            Quantity = 12,
                            SalesCount = 12,
                            UpdatedDate = "2023/08/17 16:50:59",
                            Url = "urun-12"
                        },
                        new
                        {
                            ProductId = 111111124.0,
                            CreatedDate = "2023/08/17 16:50:59",
                            Description = "urun aciklamasi 13",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 13",
                            Price = 10.0,
                            ProductImage = "1.jpg",
                            Quantity = 13,
                            SalesCount = 13,
                            UpdatedDate = "2023/08/17 16:50:59",
                            Url = "urun-13"
                        },
                        new
                        {
                            ProductId = 111111125.0,
                            CreatedDate = "2023/08/17 16:50:59",
                            Description = "urun aciklamasi 14",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 14",
                            Price = 10.0,
                            ProductImage = "1.jpg",
                            Quantity = 14,
                            SalesCount = 14,
                            UpdatedDate = "2023/08/17 16:50:59",
                            Url = "urun-14"
                        },
                        new
                        {
                            ProductId = 111111126.0,
                            CreatedDate = "2023/08/17 16:50:59",
                            Description = "urun aciklamasi 15",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 15",
                            Price = 10.0,
                            ProductImage = "1.jpg",
                            Quantity = 15,
                            SalesCount = 15,
                            UpdatedDate = "2023/08/17 16:50:59",
                            Url = "urun-15"
                        },
                        new
                        {
                            ProductId = 111111127.0,
                            CreatedDate = "2023/08/17 16:50:59",
                            Description = "urun aciklamasi 16",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 16",
                            Price = 10.0,
                            ProductImage = "1.jpg",
                            Quantity = 16,
                            SalesCount = 16,
                            UpdatedDate = "2023/08/17 16:50:59",
                            Url = "urun-16"
                        },
                        new
                        {
                            ProductId = 111111128.0,
                            CreatedDate = "2023/08/17 16:50:59",
                            Description = "urun aciklamasi 17",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 17",
                            Price = 10.0,
                            ProductImage = "1.jpg",
                            Quantity = 17,
                            SalesCount = 17,
                            UpdatedDate = "2023/08/17 16:50:59",
                            Url = "urun-17"
                        },
                        new
                        {
                            ProductId = 111111129.0,
                            CreatedDate = "2023/08/17 16:50:59",
                            Description = "urun aciklamasi 18",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 18",
                            Price = 10.0,
                            ProductImage = "1.jpg",
                            Quantity = 18,
                            SalesCount = 18,
                            UpdatedDate = "2023/08/17 16:50:59",
                            Url = "urun-18"
                        },
                        new
                        {
                            ProductId = 111111130.0,
                            CreatedDate = "2023/08/17 16:50:59",
                            Description = "urun aciklamasi 19",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 19",
                            Price = 10.0,
                            ProductImage = "1.jpg",
                            Quantity = 19,
                            SalesCount = 19,
                            UpdatedDate = "2023/08/17 16:50:59",
                            Url = "urun-19"
                        },
                        new
                        {
                            ProductId = 111111131.0,
                            CreatedDate = "2023/08/17 16:50:59",
                            Description = "urun aciklamasi 20",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 20",
                            Price = 10.0,
                            ProductImage = "1.jpg",
                            Quantity = 20,
                            SalesCount = 20,
                            UpdatedDate = "2023/08/17 16:50:59",
                            Url = "urun-20"
                        },
                        new
                        {
                            ProductId = 111111132.0,
                            CreatedDate = "2023/08/17 16:50:59",
                            Description = "urun aciklamasi 21",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 21",
                            Price = 10.0,
                            ProductImage = "1.jpg",
                            Quantity = 21,
                            SalesCount = 21,
                            UpdatedDate = "2023/08/17 16:50:59",
                            Url = "urun-21"
                        },
                        new
                        {
                            ProductId = 111111133.0,
                            CreatedDate = "2023/08/17 16:50:59",
                            Description = "urun aciklamasi 22",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 22",
                            Price = 10.0,
                            ProductImage = "1.jpg",
                            Quantity = 22,
                            SalesCount = 22,
                            UpdatedDate = "2023/08/17 16:50:59",
                            Url = "urun-22"
                        },
                        new
                        {
                            ProductId = 111111134.0,
                            CreatedDate = "2023/08/17 16:50:59",
                            Description = "urun aciklamasi 23",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 23",
                            Price = 10.0,
                            ProductImage = "1.jpg",
                            Quantity = 23,
                            SalesCount = 23,
                            UpdatedDate = "2023/08/17 16:50:59",
                            Url = "urun-23"
                        },
                        new
                        {
                            ProductId = 111111135.0,
                            CreatedDate = "2023/08/17 16:50:59",
                            Description = "urun aciklamasi 24",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 24",
                            Price = 10.0,
                            ProductImage = "1.jpg",
                            Quantity = 24,
                            SalesCount = 24,
                            UpdatedDate = "2023/08/17 16:50:59",
                            Url = "urun-24"
                        },
                        new
                        {
                            ProductId = 111111136.0,
                            CreatedDate = "2023/08/17 16:50:59",
                            Description = "urun aciklamasi 25",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 25",
                            Price = 10.0,
                            ProductImage = "1.jpg",
                            Quantity = 25,
                            SalesCount = 25,
                            UpdatedDate = "2023/08/17 16:50:59",
                            Url = "urun-25"
                        },
                        new
                        {
                            ProductId = 111111137.0,
                            CreatedDate = "2023/08/17 16:50:59",
                            Description = "urun aciklamasi 26",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 26",
                            Price = 10.0,
                            ProductImage = "1.jpg",
                            Quantity = 26,
                            SalesCount = 26,
                            UpdatedDate = "2023/08/17 16:50:59",
                            Url = "urun-26"
                        },
                        new
                        {
                            ProductId = 111111138.0,
                            CreatedDate = "2023/08/17 16:50:59",
                            Description = "urun aciklamasi 27",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 27",
                            Price = 10.0,
                            ProductImage = "1.jpg",
                            Quantity = 27,
                            SalesCount = 27,
                            UpdatedDate = "2023/08/17 16:50:59",
                            Url = "urun-27"
                        },
                        new
                        {
                            ProductId = 111111139.0,
                            CreatedDate = "2023/08/17 16:50:59",
                            Description = "urun aciklamasi 28",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 28",
                            Price = 10.0,
                            ProductImage = "1.jpg",
                            Quantity = 28,
                            SalesCount = 28,
                            UpdatedDate = "2023/08/17 16:50:59",
                            Url = "urun-28"
                        },
                        new
                        {
                            ProductId = 111111140.0,
                            CreatedDate = "2023/08/17 16:50:59",
                            Description = "urun aciklamasi 29",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 29",
                            Price = 10.0,
                            ProductImage = "1.jpg",
                            Quantity = 29,
                            SalesCount = 29,
                            UpdatedDate = "2023/08/17 16:50:59",
                            Url = "urun-29"
                        },
                        new
                        {
                            ProductId = 111111141.0,
                            CreatedDate = "2023/08/17 16:50:59",
                            Description = "urun aciklamasi 30",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 30",
                            Price = 10.0,
                            ProductImage = "1.jpg",
                            Quantity = 30,
                            SalesCount = 30,
                            UpdatedDate = "2023/08/17 16:50:59",
                            Url = "urun-30"
                        },
                        new
                        {
                            ProductId = 111111142.0,
                            CreatedDate = "2023/08/17 16:50:59",
                            Description = "urun aciklamasi 31",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 31",
                            Price = 10.0,
                            ProductImage = "1.jpg",
                            Quantity = 31,
                            SalesCount = 31,
                            UpdatedDate = "2023/08/17 16:50:59",
                            Url = "urun-31"
                        },
                        new
                        {
                            ProductId = 111111143.0,
                            CreatedDate = "2023/08/17 16:50:59",
                            Description = "urun aciklamasi 32",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 32",
                            Price = 10.0,
                            ProductImage = "1.jpg",
                            Quantity = 32,
                            SalesCount = 32,
                            UpdatedDate = "2023/08/17 16:50:59",
                            Url = "urun-32"
                        },
                        new
                        {
                            ProductId = 111111144.0,
                            CreatedDate = "2023/08/17 16:50:59",
                            Description = "urun aciklamasi 33",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 33",
                            Price = 10.0,
                            ProductImage = "1.jpg",
                            Quantity = 33,
                            SalesCount = 33,
                            UpdatedDate = "2023/08/17 16:50:59",
                            Url = "urun-33"
                        },
                        new
                        {
                            ProductId = 111111145.0,
                            CreatedDate = "2023/08/17 16:50:59",
                            Description = "urun aciklamasi 34",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 34",
                            Price = 10.0,
                            ProductImage = "1.jpg",
                            Quantity = 34,
                            SalesCount = 34,
                            UpdatedDate = "2023/08/17 16:50:59",
                            Url = "urun-34"
                        },
                        new
                        {
                            ProductId = 111111146.0,
                            CreatedDate = "2023/08/17 16:50:59",
                            Description = "urun aciklamasi 35",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 35",
                            Price = 10.0,
                            ProductImage = "1.jpg",
                            Quantity = 35,
                            SalesCount = 35,
                            UpdatedDate = "2023/08/17 16:50:59",
                            Url = "urun-35"
                        },
                        new
                        {
                            ProductId = 111111147.0,
                            CreatedDate = "2023/08/17 16:50:59",
                            Description = "urun aciklamasi 36",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 36",
                            Price = 10.0,
                            ProductImage = "1.jpg",
                            Quantity = 36,
                            SalesCount = 36,
                            UpdatedDate = "2023/08/17 16:50:59",
                            Url = "urun-36"
                        },
                        new
                        {
                            ProductId = 111111148.0,
                            CreatedDate = "2023/08/17 16:50:59",
                            Description = "urun aciklamasi 37",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 37",
                            Price = 10.0,
                            ProductImage = "1.jpg",
                            Quantity = 37,
                            SalesCount = 37,
                            UpdatedDate = "2023/08/17 16:50:59",
                            Url = "urun-37"
                        },
                        new
                        {
                            ProductId = 111111149.0,
                            CreatedDate = "2023/08/17 16:50:59",
                            Description = "urun aciklamasi 38",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 38",
                            Price = 10.0,
                            ProductImage = "1.jpg",
                            Quantity = 38,
                            SalesCount = 38,
                            UpdatedDate = "2023/08/17 16:50:59",
                            Url = "urun-38"
                        },
                        new
                        {
                            ProductId = 111111150.0,
                            CreatedDate = "2023/08/17 16:50:59",
                            Description = "urun aciklamasi 39",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 39",
                            Price = 10.0,
                            ProductImage = "1.jpg",
                            Quantity = 39,
                            SalesCount = 39,
                            UpdatedDate = "2023/08/17 16:50:59",
                            Url = "urun-39"
                        },
                        new
                        {
                            ProductId = 111111151.0,
                            CreatedDate = "2023/08/17 16:50:59",
                            Description = "urun aciklamasi 40",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 40",
                            Price = 10.0,
                            ProductImage = "1.jpg",
                            Quantity = 40,
                            SalesCount = 40,
                            UpdatedDate = "2023/08/17 16:50:59",
                            Url = "urun-40"
                        },
                        new
                        {
                            ProductId = 111111152.0,
                            CreatedDate = "2023/08/17 16:50:59",
                            Description = "urun aciklamasi 41",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 41",
                            Price = 10.0,
                            ProductImage = "1.jpg",
                            Quantity = 41,
                            SalesCount = 41,
                            UpdatedDate = "2023/08/17 16:50:59",
                            Url = "urun-41"
                        },
                        new
                        {
                            ProductId = 111111153.0,
                            CreatedDate = "2023/08/17 16:50:59",
                            Description = "urun aciklamasi 42",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 42",
                            Price = 10.0,
                            ProductImage = "1.jpg",
                            Quantity = 42,
                            SalesCount = 42,
                            UpdatedDate = "2023/08/17 16:50:59",
                            Url = "urun-42"
                        },
                        new
                        {
                            ProductId = 111111154.0,
                            CreatedDate = "2023/08/17 16:50:59",
                            Description = "urun aciklamasi 43",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 43",
                            Price = 10.0,
                            ProductImage = "1.jpg",
                            Quantity = 43,
                            SalesCount = 43,
                            UpdatedDate = "2023/08/17 16:50:59",
                            Url = "urun-43"
                        },
                        new
                        {
                            ProductId = 111111155.0,
                            CreatedDate = "2023/08/17 16:50:59",
                            Description = "urun aciklamasi 44",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 44",
                            Price = 10.0,
                            ProductImage = "1.jpg",
                            Quantity = 44,
                            SalesCount = 44,
                            UpdatedDate = "2023/08/17 16:50:59",
                            Url = "urun-44"
                        },
                        new
                        {
                            ProductId = 111111156.0,
                            CreatedDate = "2023/08/17 16:50:59",
                            Description = "urun aciklamasi 45",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 45",
                            Price = 10.0,
                            ProductImage = "1.jpg",
                            Quantity = 45,
                            SalesCount = 45,
                            UpdatedDate = "2023/08/17 16:50:59",
                            Url = "urun-45"
                        },
                        new
                        {
                            ProductId = 111111157.0,
                            CreatedDate = "2023/08/17 16:50:59",
                            Description = "urun aciklamasi 46",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 46",
                            Price = 10.0,
                            ProductImage = "1.jpg",
                            Quantity = 46,
                            SalesCount = 46,
                            UpdatedDate = "2023/08/17 16:50:59",
                            Url = "urun-46"
                        },
                        new
                        {
                            ProductId = 111111158.0,
                            CreatedDate = "2023/08/17 16:50:59",
                            Description = "urun aciklamasi 47",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 47",
                            Price = 10.0,
                            ProductImage = "1.jpg",
                            Quantity = 47,
                            SalesCount = 47,
                            UpdatedDate = "2023/08/17 16:50:59",
                            Url = "urun-47"
                        },
                        new
                        {
                            ProductId = 111111159.0,
                            CreatedDate = "2023/08/17 16:50:59",
                            Description = "urun aciklamasi 48",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 48",
                            Price = 10.0,
                            ProductImage = "1.jpg",
                            Quantity = 48,
                            SalesCount = 48,
                            UpdatedDate = "2023/08/17 16:50:59",
                            Url = "urun-48"
                        },
                        new
                        {
                            ProductId = 111111160.0,
                            CreatedDate = "2023/08/17 16:50:59",
                            Description = "urun aciklamasi 49",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 49",
                            Price = 10.0,
                            ProductImage = "1.jpg",
                            Quantity = 49,
                            SalesCount = 49,
                            UpdatedDate = "2023/08/17 16:50:59",
                            Url = "urun-49"
                        });
                });

            modelBuilder.Entity("EntityLayer.ProductCategory", b =>
                {
                    b.Property<double>("CategoryId")
                        .HasColumnType("float");

                    b.Property<double>("ProductId")
                        .HasColumnType("float");

                    b.Property<double>("Id")
                        .HasColumnType("float");

                    b.HasKey("CategoryId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            CategoryId = 111111112.0,
                            ProductId = 111111112.0,
                            Id = 116557806.0
                        },
                        new
                        {
                            CategoryId = 111111113.0,
                            ProductId = 111111113.0,
                            Id = 752698525.0
                        },
                        new
                        {
                            CategoryId = 111111114.0,
                            ProductId = 111111114.0,
                            Id = 685307395.0
                        },
                        new
                        {
                            CategoryId = 111111115.0,
                            ProductId = 111111115.0,
                            Id = 563304109.0
                        },
                        new
                        {
                            CategoryId = 111111116.0,
                            ProductId = 111111116.0,
                            Id = 722072845.0
                        },
                        new
                        {
                            CategoryId = 111111117.0,
                            ProductId = 111111117.0,
                            Id = 880317711.0
                        },
                        new
                        {
                            CategoryId = 111111118.0,
                            ProductId = 111111118.0,
                            Id = 365620929.0
                        },
                        new
                        {
                            CategoryId = 111111119.0,
                            ProductId = 111111119.0,
                            Id = 390540500.0
                        },
                        new
                        {
                            CategoryId = 111111120.0,
                            ProductId = 111111120.0,
                            Id = 946048035.0
                        });
                });

            modelBuilder.Entity("EntityLayer.CartItem", b =>
                {
                    b.HasOne("EntityLayer.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EntityLayer.ImageUrl", b =>
                {
                    b.HasOne("EntityLayer.Product", "Product")
                        .WithMany("ImageUrls")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EntityLayer.OrderItem", b =>
                {
                    b.HasOne("EntityLayer.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EntityLayer.ProductCategory", b =>
                {
                    b.HasOne("EntityLayer.Category", "Category")
                        .WithMany("ProductCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Product", "Product")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EntityLayer.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("EntityLayer.Category", b =>
                {
                    b.Navigation("ProductCategories");
                });

            modelBuilder.Entity("EntityLayer.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("EntityLayer.Product", b =>
                {
                    b.Navigation("ImageUrls");

                    b.Navigation("ProductCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
