// <auto-generated />
using System;
using DataAccessLayer.Concrete.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(ShopContext))]
    [Migration("20230815142036_mig_1")]
    partial class mig_1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EntityLayer.Cart", b =>
                {
                    b.Property<double>("CartId")
                        .HasColumnType("float");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CartId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("EntityLayer.CartItem", b =>
                {
                    b.Property<double>("CartItemId")
                        .HasColumnType("float");

                    b.Property<double>("CartId")
                        .HasColumnType("float");

                    b.Property<double>("ProductId")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("CartItemId");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("EntityLayer.Category", b =>
                {
                    b.Property<double>("CategoryId")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1.0,
                            Name = "category 1",
                            Url = "category-1"
                        },
                        new
                        {
                            CategoryId = 2.0,
                            Name = "category 2",
                            Url = "category-2"
                        },
                        new
                        {
                            CategoryId = 3.0,
                            Name = "category 3",
                            Url = "category-3"
                        },
                        new
                        {
                            CategoryId = 4.0,
                            Name = "category 4",
                            Url = "category-4"
                        },
                        new
                        {
                            CategoryId = 5.0,
                            Name = "category 5",
                            Url = "category-5"
                        },
                        new
                        {
                            CategoryId = 6.0,
                            Name = "category 6",
                            Url = "category-6"
                        },
                        new
                        {
                            CategoryId = 7.0,
                            Name = "category 7",
                            Url = "category-7"
                        },
                        new
                        {
                            CategoryId = 8.0,
                            Name = "category 8",
                            Url = "category-8"
                        },
                        new
                        {
                            CategoryId = 9.0,
                            Name = "category 9",
                            Url = "category-9"
                        });
                });

            modelBuilder.Entity("EntityLayer.Order", b =>
                {
                    b.Property<double>("OrderId")
                        .HasColumnType("float");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConversationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderState")
                        .HasColumnType("int");

                    b.Property<string>("PaymentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaymentType")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("EntityLayer.OrderItem", b =>
                {
                    b.Property<double>("OrderItemId")
                        .HasColumnType("float");

                    b.Property<double>("OrderId")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("ProductId")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("EntityLayer.Product", b =>
                {
                    b.Property<double>("ProductId")
                        .HasColumnType("float");

                    b.Property<string>("CreatedDate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHome")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<double?>("Price")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SalesCount")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1.0,
                            CreatedDate = "2023/08/15 17:20:36",
                            Description = "urun aciklamasi 1",
                            ImageUrl = "1.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 1",
                            Price = 10.0,
                            Quantity = 1,
                            SalesCount = 0,
                            UpdatedDate = "2023/08/15 17:20:36",
                            Url = "urun-1"
                        },
                        new
                        {
                            ProductId = 2.0,
                            CreatedDate = "2023/08/15 17:20:36",
                            Description = "urun aciklamasi 2",
                            ImageUrl = "1.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 2",
                            Price = 10.0,
                            Quantity = 2,
                            SalesCount = 0,
                            UpdatedDate = "2023/08/15 17:20:36",
                            Url = "urun-2"
                        },
                        new
                        {
                            ProductId = 3.0,
                            CreatedDate = "2023/08/15 17:20:36",
                            Description = "urun aciklamasi 3",
                            ImageUrl = "1.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 3",
                            Price = 10.0,
                            Quantity = 3,
                            SalesCount = 0,
                            UpdatedDate = "2023/08/15 17:20:36",
                            Url = "urun-3"
                        },
                        new
                        {
                            ProductId = 4.0,
                            CreatedDate = "2023/08/15 17:20:36",
                            Description = "urun aciklamasi 4",
                            ImageUrl = "1.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 4",
                            Price = 10.0,
                            Quantity = 4,
                            SalesCount = 0,
                            UpdatedDate = "2023/08/15 17:20:36",
                            Url = "urun-4"
                        },
                        new
                        {
                            ProductId = 5.0,
                            CreatedDate = "2023/08/15 17:20:36",
                            Description = "urun aciklamasi 5",
                            ImageUrl = "1.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 5",
                            Price = 10.0,
                            Quantity = 5,
                            SalesCount = 0,
                            UpdatedDate = "2023/08/15 17:20:36",
                            Url = "urun-5"
                        },
                        new
                        {
                            ProductId = 6.0,
                            CreatedDate = "2023/08/15 17:20:36",
                            Description = "urun aciklamasi 6",
                            ImageUrl = "1.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 6",
                            Price = 10.0,
                            Quantity = 6,
                            SalesCount = 0,
                            UpdatedDate = "2023/08/15 17:20:36",
                            Url = "urun-6"
                        },
                        new
                        {
                            ProductId = 7.0,
                            CreatedDate = "2023/08/15 17:20:36",
                            Description = "urun aciklamasi 7",
                            ImageUrl = "1.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 7",
                            Price = 10.0,
                            Quantity = 7,
                            SalesCount = 0,
                            UpdatedDate = "2023/08/15 17:20:36",
                            Url = "urun-7"
                        },
                        new
                        {
                            ProductId = 8.0,
                            CreatedDate = "2023/08/15 17:20:36",
                            Description = "urun aciklamasi 8",
                            ImageUrl = "1.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 8",
                            Price = 10.0,
                            Quantity = 8,
                            SalesCount = 0,
                            UpdatedDate = "2023/08/15 17:20:36",
                            Url = "urun-8"
                        },
                        new
                        {
                            ProductId = 9.0,
                            CreatedDate = "2023/08/15 17:20:36",
                            Description = "urun aciklamasi 9",
                            ImageUrl = "1.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 9",
                            Price = 10.0,
                            Quantity = 9,
                            SalesCount = 0,
                            UpdatedDate = "2023/08/15 17:20:36",
                            Url = "urun-9"
                        },
                        new
                        {
                            ProductId = 10.0,
                            CreatedDate = "2023/08/15 17:20:36",
                            Description = "urun aciklamasi 10",
                            ImageUrl = "1.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 10",
                            Price = 10.0,
                            Quantity = 10,
                            SalesCount = 0,
                            UpdatedDate = "2023/08/15 17:20:36",
                            Url = "urun-10"
                        },
                        new
                        {
                            ProductId = 11.0,
                            CreatedDate = "2023/08/15 17:20:36",
                            Description = "urun aciklamasi 11",
                            ImageUrl = "1.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 11",
                            Price = 10.0,
                            Quantity = 11,
                            SalesCount = 0,
                            UpdatedDate = "2023/08/15 17:20:36",
                            Url = "urun-11"
                        },
                        new
                        {
                            ProductId = 12.0,
                            CreatedDate = "2023/08/15 17:20:36",
                            Description = "urun aciklamasi 12",
                            ImageUrl = "1.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 12",
                            Price = 10.0,
                            Quantity = 12,
                            SalesCount = 0,
                            UpdatedDate = "2023/08/15 17:20:36",
                            Url = "urun-12"
                        },
                        new
                        {
                            ProductId = 13.0,
                            CreatedDate = "2023/08/15 17:20:36",
                            Description = "urun aciklamasi 13",
                            ImageUrl = "1.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 13",
                            Price = 10.0,
                            Quantity = 13,
                            SalesCount = 0,
                            UpdatedDate = "2023/08/15 17:20:36",
                            Url = "urun-13"
                        },
                        new
                        {
                            ProductId = 14.0,
                            CreatedDate = "2023/08/15 17:20:36",
                            Description = "urun aciklamasi 14",
                            ImageUrl = "1.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 14",
                            Price = 10.0,
                            Quantity = 14,
                            SalesCount = 0,
                            UpdatedDate = "2023/08/15 17:20:36",
                            Url = "urun-14"
                        },
                        new
                        {
                            ProductId = 15.0,
                            CreatedDate = "2023/08/15 17:20:36",
                            Description = "urun aciklamasi 15",
                            ImageUrl = "1.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 15",
                            Price = 10.0,
                            Quantity = 15,
                            SalesCount = 0,
                            UpdatedDate = "2023/08/15 17:20:36",
                            Url = "urun-15"
                        },
                        new
                        {
                            ProductId = 16.0,
                            CreatedDate = "2023/08/15 17:20:36",
                            Description = "urun aciklamasi 16",
                            ImageUrl = "1.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 16",
                            Price = 10.0,
                            Quantity = 16,
                            SalesCount = 0,
                            UpdatedDate = "2023/08/15 17:20:36",
                            Url = "urun-16"
                        },
                        new
                        {
                            ProductId = 17.0,
                            CreatedDate = "2023/08/15 17:20:36",
                            Description = "urun aciklamasi 17",
                            ImageUrl = "1.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 17",
                            Price = 10.0,
                            Quantity = 17,
                            SalesCount = 0,
                            UpdatedDate = "2023/08/15 17:20:36",
                            Url = "urun-17"
                        },
                        new
                        {
                            ProductId = 18.0,
                            CreatedDate = "2023/08/15 17:20:36",
                            Description = "urun aciklamasi 18",
                            ImageUrl = "1.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 18",
                            Price = 10.0,
                            Quantity = 18,
                            SalesCount = 0,
                            UpdatedDate = "2023/08/15 17:20:36",
                            Url = "urun-18"
                        },
                        new
                        {
                            ProductId = 19.0,
                            CreatedDate = "2023/08/15 17:20:36",
                            Description = "urun aciklamasi 19",
                            ImageUrl = "1.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 19",
                            Price = 10.0,
                            Quantity = 19,
                            SalesCount = 0,
                            UpdatedDate = "2023/08/15 17:20:36",
                            Url = "urun-19"
                        },
                        new
                        {
                            ProductId = 20.0,
                            CreatedDate = "2023/08/15 17:20:36",
                            Description = "urun aciklamasi 20",
                            ImageUrl = "1.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 20",
                            Price = 10.0,
                            Quantity = 20,
                            SalesCount = 0,
                            UpdatedDate = "2023/08/15 17:20:36",
                            Url = "urun-20"
                        },
                        new
                        {
                            ProductId = 21.0,
                            CreatedDate = "2023/08/15 17:20:36",
                            Description = "urun aciklamasi 21",
                            ImageUrl = "1.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 21",
                            Price = 10.0,
                            Quantity = 21,
                            SalesCount = 0,
                            UpdatedDate = "2023/08/15 17:20:36",
                            Url = "urun-21"
                        },
                        new
                        {
                            ProductId = 22.0,
                            CreatedDate = "2023/08/15 17:20:36",
                            Description = "urun aciklamasi 22",
                            ImageUrl = "1.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 22",
                            Price = 10.0,
                            Quantity = 22,
                            SalesCount = 0,
                            UpdatedDate = "2023/08/15 17:20:36",
                            Url = "urun-22"
                        },
                        new
                        {
                            ProductId = 23.0,
                            CreatedDate = "2023/08/15 17:20:36",
                            Description = "urun aciklamasi 23",
                            ImageUrl = "1.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 23",
                            Price = 10.0,
                            Quantity = 23,
                            SalesCount = 0,
                            UpdatedDate = "2023/08/15 17:20:36",
                            Url = "urun-23"
                        },
                        new
                        {
                            ProductId = 24.0,
                            CreatedDate = "2023/08/15 17:20:36",
                            Description = "urun aciklamasi 24",
                            ImageUrl = "1.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 24",
                            Price = 10.0,
                            Quantity = 24,
                            SalesCount = 0,
                            UpdatedDate = "2023/08/15 17:20:36",
                            Url = "urun-24"
                        },
                        new
                        {
                            ProductId = 25.0,
                            CreatedDate = "2023/08/15 17:20:36",
                            Description = "urun aciklamasi 25",
                            ImageUrl = "1.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 25",
                            Price = 10.0,
                            Quantity = 25,
                            SalesCount = 0,
                            UpdatedDate = "2023/08/15 17:20:36",
                            Url = "urun-25"
                        },
                        new
                        {
                            ProductId = 26.0,
                            CreatedDate = "2023/08/15 17:20:36",
                            Description = "urun aciklamasi 26",
                            ImageUrl = "1.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 26",
                            Price = 10.0,
                            Quantity = 26,
                            SalesCount = 0,
                            UpdatedDate = "2023/08/15 17:20:36",
                            Url = "urun-26"
                        },
                        new
                        {
                            ProductId = 27.0,
                            CreatedDate = "2023/08/15 17:20:36",
                            Description = "urun aciklamasi 27",
                            ImageUrl = "1.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 27",
                            Price = 10.0,
                            Quantity = 27,
                            SalesCount = 0,
                            UpdatedDate = "2023/08/15 17:20:36",
                            Url = "urun-27"
                        },
                        new
                        {
                            ProductId = 28.0,
                            CreatedDate = "2023/08/15 17:20:36",
                            Description = "urun aciklamasi 28",
                            ImageUrl = "1.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 28",
                            Price = 10.0,
                            Quantity = 28,
                            SalesCount = 0,
                            UpdatedDate = "2023/08/15 17:20:36",
                            Url = "urun-28"
                        },
                        new
                        {
                            ProductId = 29.0,
                            CreatedDate = "2023/08/15 17:20:36",
                            Description = "urun aciklamasi 29",
                            ImageUrl = "1.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 29",
                            Price = 10.0,
                            Quantity = 29,
                            SalesCount = 0,
                            UpdatedDate = "2023/08/15 17:20:36",
                            Url = "urun-29"
                        },
                        new
                        {
                            ProductId = 30.0,
                            CreatedDate = "2023/08/15 17:20:36",
                            Description = "urun aciklamasi 30",
                            ImageUrl = "1.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 30",
                            Price = 10.0,
                            Quantity = 30,
                            SalesCount = 0,
                            UpdatedDate = "2023/08/15 17:20:36",
                            Url = "urun-30"
                        },
                        new
                        {
                            ProductId = 31.0,
                            CreatedDate = "2023/08/15 17:20:36",
                            Description = "urun aciklamasi 31",
                            ImageUrl = "1.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 31",
                            Price = 10.0,
                            Quantity = 31,
                            SalesCount = 0,
                            UpdatedDate = "2023/08/15 17:20:36",
                            Url = "urun-31"
                        },
                        new
                        {
                            ProductId = 32.0,
                            CreatedDate = "2023/08/15 17:20:36",
                            Description = "urun aciklamasi 32",
                            ImageUrl = "1.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 32",
                            Price = 10.0,
                            Quantity = 32,
                            SalesCount = 0,
                            UpdatedDate = "2023/08/15 17:20:36",
                            Url = "urun-32"
                        },
                        new
                        {
                            ProductId = 33.0,
                            CreatedDate = "2023/08/15 17:20:36",
                            Description = "urun aciklamasi 33",
                            ImageUrl = "1.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 33",
                            Price = 10.0,
                            Quantity = 33,
                            SalesCount = 0,
                            UpdatedDate = "2023/08/15 17:20:36",
                            Url = "urun-33"
                        },
                        new
                        {
                            ProductId = 34.0,
                            CreatedDate = "2023/08/15 17:20:36",
                            Description = "urun aciklamasi 34",
                            ImageUrl = "1.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 34",
                            Price = 10.0,
                            Quantity = 34,
                            SalesCount = 0,
                            UpdatedDate = "2023/08/15 17:20:36",
                            Url = "urun-34"
                        },
                        new
                        {
                            ProductId = 35.0,
                            CreatedDate = "2023/08/15 17:20:36",
                            Description = "urun aciklamasi 35",
                            ImageUrl = "1.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 35",
                            Price = 10.0,
                            Quantity = 35,
                            SalesCount = 0,
                            UpdatedDate = "2023/08/15 17:20:36",
                            Url = "urun-35"
                        },
                        new
                        {
                            ProductId = 36.0,
                            CreatedDate = "2023/08/15 17:20:36",
                            Description = "urun aciklamasi 36",
                            ImageUrl = "1.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 36",
                            Price = 10.0,
                            Quantity = 36,
                            SalesCount = 0,
                            UpdatedDate = "2023/08/15 17:20:36",
                            Url = "urun-36"
                        },
                        new
                        {
                            ProductId = 37.0,
                            CreatedDate = "2023/08/15 17:20:36",
                            Description = "urun aciklamasi 37",
                            ImageUrl = "1.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 37",
                            Price = 10.0,
                            Quantity = 37,
                            SalesCount = 0,
                            UpdatedDate = "2023/08/15 17:20:36",
                            Url = "urun-37"
                        },
                        new
                        {
                            ProductId = 38.0,
                            CreatedDate = "2023/08/15 17:20:36",
                            Description = "urun aciklamasi 38",
                            ImageUrl = "1.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 38",
                            Price = 10.0,
                            Quantity = 38,
                            SalesCount = 0,
                            UpdatedDate = "2023/08/15 17:20:36",
                            Url = "urun-38"
                        },
                        new
                        {
                            ProductId = 39.0,
                            CreatedDate = "2023/08/15 17:20:36",
                            Description = "urun aciklamasi 39",
                            ImageUrl = "1.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 39",
                            Price = 10.0,
                            Quantity = 39,
                            SalesCount = 0,
                            UpdatedDate = "2023/08/15 17:20:36",
                            Url = "urun-39"
                        },
                        new
                        {
                            ProductId = 40.0,
                            CreatedDate = "2023/08/15 17:20:36",
                            Description = "urun aciklamasi 40",
                            ImageUrl = "1.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 40",
                            Price = 10.0,
                            Quantity = 40,
                            SalesCount = 0,
                            UpdatedDate = "2023/08/15 17:20:36",
                            Url = "urun-40"
                        },
                        new
                        {
                            ProductId = 41.0,
                            CreatedDate = "2023/08/15 17:20:36",
                            Description = "urun aciklamasi 41",
                            ImageUrl = "1.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 41",
                            Price = 10.0,
                            Quantity = 41,
                            SalesCount = 0,
                            UpdatedDate = "2023/08/15 17:20:36",
                            Url = "urun-41"
                        },
                        new
                        {
                            ProductId = 42.0,
                            CreatedDate = "2023/08/15 17:20:36",
                            Description = "urun aciklamasi 42",
                            ImageUrl = "1.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 42",
                            Price = 10.0,
                            Quantity = 42,
                            SalesCount = 0,
                            UpdatedDate = "2023/08/15 17:20:36",
                            Url = "urun-42"
                        },
                        new
                        {
                            ProductId = 43.0,
                            CreatedDate = "2023/08/15 17:20:36",
                            Description = "urun aciklamasi 43",
                            ImageUrl = "1.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 43",
                            Price = 10.0,
                            Quantity = 43,
                            SalesCount = 0,
                            UpdatedDate = "2023/08/15 17:20:36",
                            Url = "urun-43"
                        },
                        new
                        {
                            ProductId = 44.0,
                            CreatedDate = "2023/08/15 17:20:36",
                            Description = "urun aciklamasi 44",
                            ImageUrl = "1.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 44",
                            Price = 10.0,
                            Quantity = 44,
                            SalesCount = 0,
                            UpdatedDate = "2023/08/15 17:20:36",
                            Url = "urun-44"
                        },
                        new
                        {
                            ProductId = 45.0,
                            CreatedDate = "2023/08/15 17:20:36",
                            Description = "urun aciklamasi 45",
                            ImageUrl = "1.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 45",
                            Price = 10.0,
                            Quantity = 45,
                            SalesCount = 0,
                            UpdatedDate = "2023/08/15 17:20:36",
                            Url = "urun-45"
                        },
                        new
                        {
                            ProductId = 46.0,
                            CreatedDate = "2023/08/15 17:20:36",
                            Description = "urun aciklamasi 46",
                            ImageUrl = "1.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 46",
                            Price = 10.0,
                            Quantity = 46,
                            SalesCount = 0,
                            UpdatedDate = "2023/08/15 17:20:36",
                            Url = "urun-46"
                        },
                        new
                        {
                            ProductId = 47.0,
                            CreatedDate = "2023/08/15 17:20:36",
                            Description = "urun aciklamasi 47",
                            ImageUrl = "1.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 47",
                            Price = 10.0,
                            Quantity = 47,
                            SalesCount = 0,
                            UpdatedDate = "2023/08/15 17:20:36",
                            Url = "urun-47"
                        },
                        new
                        {
                            ProductId = 48.0,
                            CreatedDate = "2023/08/15 17:20:36",
                            Description = "urun aciklamasi 48",
                            ImageUrl = "1.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 48",
                            Price = 10.0,
                            Quantity = 48,
                            SalesCount = 0,
                            UpdatedDate = "2023/08/15 17:20:36",
                            Url = "urun-48"
                        },
                        new
                        {
                            ProductId = 49.0,
                            CreatedDate = "2023/08/15 17:20:36",
                            Description = "urun aciklamasi 49",
                            ImageUrl = "1.jpg",
                            IsApproved = true,
                            IsHome = false,
                            Name = "urun 49",
                            Price = 10.0,
                            Quantity = 49,
                            SalesCount = 0,
                            UpdatedDate = "2023/08/15 17:20:36",
                            Url = "urun-49"
                        });
                });

            modelBuilder.Entity("EntityLayer.ProductCategory", b =>
                {
                    b.Property<double>("CategoryId")
                        .HasColumnType("float");

                    b.Property<double>("ProductId")
                        .HasColumnType("float");

                    b.Property<double>("Id")
                        .HasColumnType("float");

                    b.HasKey("CategoryId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1.0,
                            ProductId = 1.0,
                            Id = 0.074962908062155442
                        },
                        new
                        {
                            CategoryId = 2.0,
                            ProductId = 2.0,
                            Id = 0.053908470734938763
                        },
                        new
                        {
                            CategoryId = 3.0,
                            ProductId = 3.0,
                            Id = 0.50657643527102592
                        },
                        new
                        {
                            CategoryId = 4.0,
                            ProductId = 4.0,
                            Id = 0.10249034288847125
                        },
                        new
                        {
                            CategoryId = 5.0,
                            ProductId = 5.0,
                            Id = 0.24261805974186945
                        },
                        new
                        {
                            CategoryId = 6.0,
                            ProductId = 6.0,
                            Id = 0.40044998854791214
                        },
                        new
                        {
                            CategoryId = 7.0,
                            ProductId = 7.0,
                            Id = 0.59959590546627461
                        },
                        new
                        {
                            CategoryId = 8.0,
                            ProductId = 8.0,
                            Id = 0.28030444441775559
                        },
                        new
                        {
                            CategoryId = 9.0,
                            ProductId = 9.0,
                            Id = 0.84461017102497216
                        });
                });

            modelBuilder.Entity("EntityLayer.CartItem", b =>
                {
                    b.HasOne("EntityLayer.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EntityLayer.OrderItem", b =>
                {
                    b.HasOne("EntityLayer.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EntityLayer.ProductCategory", b =>
                {
                    b.HasOne("EntityLayer.Category", "Category")
                        .WithMany("ProductCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Product", "Product")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EntityLayer.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("EntityLayer.Category", b =>
                {
                    b.Navigation("ProductCategories");
                });

            modelBuilder.Entity("EntityLayer.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("EntityLayer.Product", b =>
                {
                    b.Navigation("ProductCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
